=== DenisPan007/XmlParsing/src/test/resources/device_files/DevicesXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/devices"
        xmlns:tns="http://www.example.com/devices"
        elementFormDefault="qualified">
    <element name="devices">
        <complexType>
            <sequence>
                <element name="device"
                         type="tns:Device"
                         minOccurs="0"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Device">
        <sequence>
            <element name="component"
                     type="tns:Component"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
        <attribute name="ID" type="ID" use="required" />
    </complexType>

    <complexType name="Component">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <minLength value="3"/>
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="country">
                <simpleType>
                    <restriction base="string">
                        <minLength value="2"/>
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="price" type="positiveInteger"/>
            <element name="peripheral" type="boolean"/>
            <element name="power_Consumption_Watt" type="positiveInteger"/>
            <element name="port">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="COM"></enumeration>
                        <enumeration value="USB"></enumeration>
                        <enumeration value="LPT"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="critical" type="boolean"/>
        </sequence>
    </complexType>
</schema>

=== DenisPan007/XmlParsing/src/test/resources/device_files/InvalidDevice.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/devices"
          xsi:schemaLocation="http://www.example.com/devices  DevicesXSD.xsd">

    <device ID = "ID_1" >
        <component>
            <name>Block</name>
            <country>Russia</country>
            <price>2</price>
            <!--INVALID ELEMENT--> <price/>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Monitor</name>
            <country>Russia</country>
            <price>10</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>3</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
    </device>
    <device ID = "ID_2" >
        <component>
            <name>Display</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>10</power_Consumption_Watt>
            <port>USB</port>
            <critical>true</critical>
        </component>
    </device>
    <device ID = "ID_3" >
        <component>
            <name>Block</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Mouse</name>
            <country>USA</country>
            <price>3</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Printer</name>
            <country>USA</country>
            <price>10</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
    </device>

</devices>

=== DenisPan007/XmlParsing/src/test/resources/device_files/Devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/devices"
          xsi:schemaLocation="http://www.example.com/devices DevicesXSD.xsd">

    <device ID = "ID_1" >
        <component>
            <name>Block</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Monitor</name>
            <country>Russia</country>
            <price>10</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>3</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
    </device>
    <device ID = "ID_2" >
        <component>
            <name>Display</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>10</power_Consumption_Watt>
            <port>USB</port>
            <critical>true</critical>
        </component>
    </device>
    <device ID = "ID_3" >
        <component>
            <name>Block</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Mouse</name>
            <country>USA</country>
            <price>3</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Printer</name>
            <country>USA</country>
            <price>10</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
    </device>
    <device ID = "ID_4" >
        <component>
            <name>Block</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>3</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Monitor</name>
            <country>England</country>
            <price>10</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>3</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Printer</name>
            <country>USA</country>
            <price>15</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Keyboard</name>
            <country>China</country>
            <price>20</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
    </device>
    <device ID = "ID_5" >
        <component>
            <name>Block</name>
            <country>China</country>
            <price>20</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Display</name>
            <country>Russia</country>
            <price>22</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>10</power_Consumption_Watt>
            <port>USB</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Mouse</name>
            <country>Russia</country>
            <price>3</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>LPT</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Webcam</name>
            <country>England</country>
            <price>5</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>3</power_Consumption_Watt>
            <port>USB</port>
            <critical>false</critical>
        </component>
    </device>
    <device ID="ID_6">
        <component>
            <name>Display</name>
            <country>USA</country>
            <price>20</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>4</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Block</name>
            <country>China</country>
            <price>30</price>
            <peripheral>false</peripheral>
            <power_Consumption_Watt>30</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Webcam</name>
            <country>England</country>
            <price>10</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>3</power_Consumption_Watt>
            <port>USB</port>
            <critical>false</critical>
        </component>
    </device>
</devices>

=== DenisPan007/XmlParsing/src/main/resources/Devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/devices"
          xsi:schemaLocation="http://www.example.com/devices  DevicesXSD.xsd">

    <device ID = "ID_1" >
        <component>
            <name>Block</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
        <component>
            <name>Fffff</name>
            <country>Russia</country>
            <price>2</price>
            <peripheral>true</peripheral>
            <power_Consumption_Watt>2</power_Consumption_Watt>
            <port>COM</port>
            <critical>true</critical>
        </component>
    </device>

</devices>
